# Generated by Django 5.2.2 on 2025-11-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudinformacion',
            name='codigo_seguimiento',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitudinformacion',
            name='estado',
            field=models.CharField(choices=[('no_revisada', 'No revisada'), ('revisada', 'Revisada por experto'), ('asignada', 'Experto asignado'), ('cotizada', 'Cotización generada'), ('enviada', 'Cotización enviada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('pagada', 'Pagada')], default='no_revisada', max_length=20),
        ),
    ]
