# Generated by Django 5.2.2 on 2025-06-05 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Clave interna (ej: ancho_m2, horas_mano_obra, incluir_iluminacion).', max_length=50)),
                ('etiqueta', models.CharField(help_text="Texto que verá el cliente (ej: 'Ancho en metros', 'Mano de obra (horas)').", max_length=100)),
                ('tipo', models.CharField(choices=[('unidad', 'Cantidad (unidades)'), ('boolean', 'Opción sí/no')], default='unidad', help_text="Elige 'Cantidad' o 'Opción sí/no'.", max_length=10)),
                ('precio_por_unidad', models.DecimalField(decimal_places=2, help_text='Costo por cada unidad, o costo fijo si es boolean.', max_digits=10)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspectos', to='core.servicio')),
            ],
        ),
    ]
