# Generated by Django 5.2.2 on 2025-06-05 13:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aspecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='aspecto',
            name='etiqueta',
            field=models.CharField(help_text="Texto que verá el cliente (ej: 'Ancho en metros', 'Mano de obra (horas)', 'Tipo de madera').", max_length=100),
        ),
        migrations.AlterField(
            model_name='aspecto',
            name='nombre',
            field=models.CharField(help_text='Clave interna (ej: ancho_m2, horas_mano_obra, incluir_iluminacion, tipo_madera).', max_length=50),
        ),
        migrations.AlterField(
            model_name='aspecto',
            name='precio_por_unidad',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo por cada unidad, o costo fijo si es boolean. No se usa si el tipo es selección múltiple.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='aspecto',
            name='tipo',
            field=models.CharField(choices=[('unidad', 'Cantidad (unidades)'), ('boolean', 'Opción sí/no'), ('multiple', 'Selección múltiple')], default='unidad', help_text="Elige 'Cantidad', 'Opción sí/no' o 'Selección múltiple'.", max_length=10),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('descripcion_trabajo', models.TextField()),
                ('metros_cuadrados', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fuente_cliente_url', models.URLField(blank=True, help_text='Ingrese el enlace de la página donde encontró el precio', null=True)),
                ('fuente_cliente_archivo', models.FileField(blank=True, help_text='Adjunte un archivo con la referencia del precio (opcional)', null=True, upload_to='cotizaciones/fuentes/')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='OpcionMultiple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ej: 'Madera Pino', 'Madera Teak'", max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio específico para esta opción', max_digits=10)),
                ('fuente_precio', models.CharField(blank=True, help_text='Fuente o link del precio', max_length=250, null=True)),
                ('aspecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='core.aspecto')),
            ],
        ),
    ]
