# Generated by Django 5.2.2 on 2025-06-05 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_servicio_imagen_alter_aspecto_etiqueta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='servicios/'),
        ),
        migrations.CreateModel(
            name='RespuestaAspecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_unidad', models.DecimalField(blank=True, decimal_places=2, help_text="Ingrese el precio encontrado (solo para 'unidad' y 'boolean'). Para 'selección múltiple', seleccione una opción.", max_digits=10, null=True)),
                ('aspecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aspecto')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cotizacion')),
                ('opcion_multiple', models.ForeignKey(blank=True, help_text="Selecciona una opción para 'selección múltiple'.", null=True, on_delete=django.db.models.deletion.CASCADE, to='core.opcionmultiple')),
            ],
        ),
    ]
