# Generated by Django 5.2.2 on 2025-11-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_presupuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudinformacion',
            name='comentarios_cambios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
