# Generated by Django 5.2.2 on 2025-06-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_servicio_imagen_respuestaaspecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudInformacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('cuando_comenzar', models.CharField(max_length=50)),
                ('requerimientos', models.TextField()),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
