# Generated by Django 5.2.2 on 2025-06-05 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_solicitudinformacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestaaspecto',
            name='aspecto',
        ),
        migrations.RemoveField(
            model_name='opcionmultiple',
            name='aspecto',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='respuestaaspecto',
            name='cotizacion',
        ),
        migrations.RemoveField(
            model_name='respuestaaspecto',
            name='opcion_multiple',
        ),
        migrations.RemoveField(
            model_name='solicitudinformacion',
            name='fecha_solicitud',
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='servicios/', verbose_name='Imagen del Servicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Nombre del Servicio'),
        ),
        migrations.AlterField(
            model_name='solicitudinformacion',
            name='cuando_comenzar',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudinformacion',
            name='telefono',
            field=models.CharField(default=56900000000, help_text='Ingrese el teléfono en formato 569XXXXXXXX', max_length=12, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener el formato 569 seguido de 8 números. Ejemplo: 56931931429', regex='^569\\d{8}$')]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Aspecto',
        ),
        migrations.DeleteModel(
            name='Cotizacion',
        ),
        migrations.DeleteModel(
            name='OpcionMultiple',
        ),
        migrations.DeleteModel(
            name='RespuestaAspecto',
        ),
    ]
