# Generated by Django 5.2.2 on 2025-06-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_imagenservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudinformacion',
            name='estado',
            field=models.CharField(choices=[('no_revisada', 'No revisada'), ('revisada', 'Revisada')], default='no_revisada', max_length=20),
        ),
    ]
